# Generated by Django 3.0 on 2019-12-09 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20191209_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MasterGroupSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_until', models.DateField(verbose_name='Подписка активна до')),
                ('master_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.MasterGroup', verbose_name='Мастер-группа')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Подписка на курс',
                'verbose_name_plural': 'Подписки на курс',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='curators',
        ),
        migrations.DeleteModel(
            name='CourseSubscribe',
        ),
        migrations.AddField(
            model_name='mastergroup',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='mastergroup',
            name='curators',
            field=models.ManyToManyField(related_name='curators', to=settings.AUTH_USER_MODEL, verbose_name='Кураторы'),
        ),
    ]
