# Generated by Django 3.0 on 2019-12-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191207_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscribe',
            name='subscribed_until',
            field=models.DateField(auto_now_add=True),
        ),
    ]
