# Generated by Django 3.0 on 2019-12-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191205_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
