# Generated by Django 3.0 on 2019-12-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
