# Generated by Django 3.0 on 2019-12-08 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '__first__'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название работы')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Описание работы')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='HWType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Статус задания')),
            ],
            options={
                'verbose_name': 'Статус ДЗ',
                'verbose_name_plural': 'Статусы ДЗ',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название задания')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Описание задания')),
                ('right_answer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Правильный ответ')),
                ('max_result', models.IntegerField(verbose_name='Максимальный балл')),
                ('current_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.HW', verbose_name='К какому ДЗ относится')),
                ('support_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='Прикрепить изображение')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='HWResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.DateField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.HWType', verbose_name='Статус проверки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_case', models.TextField(max_length=1000, null=True, verbose_name='Ваш ответ')),
                ('current_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.Task', verbose_name='Задание')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.HWResult')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
