# Generated by Django 3.0 on 2019-12-08 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0006_auto_20191207_1314'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название работы', max_length=100)),
                ('title', models.CharField(help_text='Описание работы', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(help_text='Дедлайн')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='HWType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Статус задания', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название задания', max_length=100)),
                ('text', models.CharField(help_text='Описание задания', max_length=500)),
                ('right_answer', models.CharField(help_text='Описание задания', max_length=500)),
                ('max_result', models.IntegerField(help_text='Максимальное количество баллов за задание')),
                ('current_work', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homework.HW')),
                ('support_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='HWResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.DateField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homework.HWType')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_case', models.CharField(help_text='Ваш ответ', max_length=1000)),
                ('current_task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homework.Task')),
                ('result', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homework.HWResult')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
