# Generated by Django 3.0 on 2019-12-08 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0006_auto_20191207_1314'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hw',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.AddField(
            model_name='hw',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание работы'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание задания'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='current_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.Task'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.HWResult'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='your_case',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ваш ответ'),
        ),
        migrations.AlterField(
            model_name='hw',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='hw',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hw',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='hwresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.HWType'),
        ),
        migrations.AlterField(
            model_name='hwresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hwtype',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Статус задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='current_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.HW'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_result',
            field=models.IntegerField(verbose_name='Максимальный балл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='right_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='support_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название задания'),
        ),
    ]
