# Generated by Django 3.0 on 2019-12-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AlterField(
            model_name='hwresult',
            name='finish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
