# Generated by Django 3.0 on 2019-12-08 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191207_1326'),
        ('media', '0006_auto_20191207_1314'),
        ('homework', '0002_auto_20191208_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hwtype',
            options={'verbose_name': 'Статус ДЗ', 'verbose_name_plural': 'Статусы ДЗ'},
        ),
        migrations.AddField(
            model_name='hw',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='current_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.Task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='your_case',
            field=models.TextField(max_length=1000, null=True, verbose_name='Ваш ответ'),
        ),
        migrations.AlterField(
            model_name='hw',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='current_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homework.HW', verbose_name='К какому ДЗ относится'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='right_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='support_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Image', verbose_name='Прикрепить изображение'),
        ),
    ]
