# Generated by Django 3.0 on 2019-12-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='', help_text='Название директории', max_length=100),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='children',
            field=models.ForeignKey(blank=True, help_text='Поддиректории', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Catalog'),
        ),
    ]
