# Generated by Django 3.0 on 2019-12-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20191207_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='children',
        ),
        migrations.AddField(
            model_name='catalog',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Наддиректория', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Catalog'),
        ),
    ]
