# Generated by Django 3.0 on 2019-12-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20191207_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='preview',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(help_text='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='Ссылка (youtube)'),
        ),
    ]
